### ISSUE TITLE
About the action space of Feedback Policy

### ISSUE THREAD

**Issue by gouyinghong** [OpenDriveLab/CLOVER#6]
Hi, I assume that the action space of the Feedback policy is defined relative to the gripper frame coordinate. During training, five frames are selected, with the last frame serving as the goal and the other frames as the current state for action prediction. However, why is the `rel_action` of current frame considered the ground truth? Isn’t `rel_action` supposed to represent the end-effector state of the current frame? I would greatly appreciate it if you could help clarify this.
![image](https://github.com/user-attachments/assets/95988d8c-be28-4627-9ae4-770261720075)

**Comment by retsuh-bqw** [comment]
Good question. We chose the relative action space in CALVIN for the following two reasons: 

1. It simply works better in CALVIN. You can try using absolute actions in CALVIN as implemented in [this line of code](https://github.com/OpenDriveLab/CLOVER/blob/92324ed0fbe563fcb272bed18522a34580958bdc/FeedbackPolicy/eval/eval_utils.py#L387). The end-effector may move very fast and unstable, but relative actions would be fine. 
2. The policy network would have enough capacity to learn the transformation of coordinates.
